# Generated by Django 5.0.1 on 2024-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_track_coperformer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='coperformer',
            field=models.CharField(blank=True, max_length=112, null=True, verbose_name='Соисполнитель'),
        ),
    ]
