# Generated by Django 5.0.1 on 2024-01-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='track',
            new_name='image',
        ),
    ]
