# Generated by Django 5.0.1 on 2024-01-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_track_like_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='image',
            new_name='track',
        ),
    ]
